context:
  version: 11.0.0

package:
  name: remark-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/remark-cli/-/remark-cli-${{ version }}.tgz
  sha256: e80db4dda173a948c0a2bd9c4752ed854e55ec521da5abe7feeb2ebb7092909d

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - remark --help

about:
  license: MIT
  license_file:
    - license
    - third-party-licenses.txt
  summary: remark is a popular tool that transforms markdown with plugins
  homepage: https://remark.js.org/
  repository: https://github.com/remarkjs/remark

extra:
  recipe-maintainers:
    - danielnachun
